### ISSUE TITLE
breaking code

### ISSUE THREAD

**Issue by kbytin** [EverledgerIO/postcss-automath#2]
I've tried your plugin and it is working wierd. 

in case: 
`height: calc(100vh - 60px)`

it compiles to: 
`height: 40vh`

**Comment by pospi** [comment]
Hey, thanks for the bug report. What you're seeing there is [LESS' math behaviour](http://lesscss.org/features/#features-overview-feature-operations), which simply coerces units to the first available value. `100vh - 60px` is actually a pretty nonsensical statement unless the CSS is being parsed in the browser where it can tell how tall the window is.

It seems what we need to do then is ignore expressions found inside `calc()` functions, so that the W3C math behaviour can take over and run the operation as expected in the browser. If you're using a PostCSS calc plugin then this one is likely interfering. Not a high priority for us in our pipeline, but at least we know what the issue is and can fix it when there's time to!

**Comment by kbytin** [comment]
I'm switching from Scss to PostCSS  and I thought about using this plugin because some math were used in style files. 

But now I'm converting all this math to calc() with Postcss plugin. Much work, but bulletproof result
